### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by daslicht** [sb-minimal/docker-ubuntu-apache-php#1]
Hi, 
when I try to start the image I get :

```
daslicht:bash_completion.d daslicht$ docker run sbminimal/docker-ubuntu-apache-php:latest 
/apache2.sh: 22: exec: /usr/sbin/apache2: not found
```

Whats wrong, please?

**Comment by sb-minimal** [comment]
updated php version made problems. should be fixed now.
Thanks for the info!

**Comment by daslicht** [comment]
Thank you , I will try it later.

One offtopic question please, how do I sync folders with my host OS ?
I am using OSX and I tried Kitematic but teh official docs and the software seam to be not in sync :)

see gitter: mitchellh/vagrant

**Comment by sb-minimal** [comment]
i can only speak for docker cli: use docker volumes to mount host folders into docker containers.
for example:

```
docker run -p 80:80 -v /path/on/host:/var/www/html sbminimal/docker-ubuntu-apache-php
```

will run apache listening on port 80 with the local directory /path/on/host mounted to /var/www/html in the apache container.

see https://docs.docker.com/v1.10/engine/userguide/containers/dockervolumes/ for more details.

**Comment by daslicht** [comment]
thank you!
