### ISSUE TITLE
i would like to see apache error_log  file 

### ISSUE THREAD

**Issue by kaingeyy** [sb-minimal/docker-ubuntu-apache-php#2]
I can't find apache error_log file , how to find this file ?

**Comment by kaingeyy** [comment]
i would add file type .ecgi to apache config file

**Comment by sb-minimal** [comment]
default logs go to /var/log/apache2/ inside the container (so you could either mount this directory to some directory on your host, or access the logs from inside the container).

Basically you can change the configuration by basing your image on sb-minimal/docker-ubuntu-apache-php and adding your custom config files.

Create a Dockerfile, containing:

```
FROM sbminimal/docker-ubuntu-apache-php
ADD overlay/ /
```

and place your custom configfiles in ./overlay/etc/apache2 .
You might for example want to overwrite ./overlay/etc/apache2/sites-available/000-default.conf

Hope this helps and points you in the right direction.

**Comment by kaingeyy** [comment]
thank you very much!
